export enum InvoiceStatus {
  FUNDING_REQUESTED = 'FUNDING_REQUESTED',
  FUNDING_RESPONSE_PENDING = 'FUNDING_RESPONSE_PENDING',
  FUNDING_RESPONSE_DECISION_PENDING = 'FUNDING_RESPONSE_DECISION_PENDING',
  FUNDING_RESPONSE_ACCEPTED = 'FUNDING_RESPONSE_ACCEPTED',
  FUNDING_PAYMENT_REJECTED = 'FUNDING_PAYMENT_REJECTED',
}

export const InvoiceStatuses: InvoiceStatus[] = [
  InvoiceStatus.FUNDING_REQUESTED,
  InvoiceStatus.FUNDING_RESPONSE_PENDING,
  InvoiceStatus.FUNDING_RESPONSE_DECISION_PENDING,
  InvoiceStatus.FUNDING_RESPONSE_ACCEPTED,
  InvoiceStatus.FUNDING_PAYMENT_REJECTED,
];
